Update DAST workflow for improved logging and cleanup

diff --git a/.github/workflows/dast.yml b/.github/workflows/dast.yml
--- a/.github/workflows/dast.yml
+++ b/.github/workflows/dast.yml
@@ -22,9 +22,10 @@ jobs:
   dast-scan:
     name: DAST Scan
     runs-on: ubuntu-latest
+
     steps:
-      - name: Log in to the Container registry
-        uses: docker/login-action@v2.1.0
+      - name: Log in to GHCR
+        uses: docker/login-action@v2
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
@@ -37,7 +38,7 @@ jobs:
             TAG="${{ github.event.inputs.image-tag }}"
           fi
           if [ -z "$TAG" ]; then
-            echo "::error::No se proporcionó image-tag."
+            echo "::error::No se proporcionó image-tag"
             exit 1
           fi
           echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
@@ -45,38 +46,36 @@ jobs:
       - name: Pull Docker Image
         run: docker pull ${{ env.IMAGE_TAG }}
 
-      - name: Start demo app container
-        # Mapeamos puerto 8080 (GitHub) -> 3000 (Tu App Next.js)
+      - name: Start App Container
         run: |
-          docker rm demoApp || true 
+          docker rm demoApp || true
           docker run -d -p 8080:3000 --name demoApp ${{ env.IMAGE_TAG }}
 
-      - name: Wait for container to start
+      - name: Wait for App
         run: |
-          echo "Waiting for http://localhost:8080..."
-          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8080)" != "200" ]]; do sleep 5; done' || false
+          echo "Waiting for app..."
+          timeout 60 bash -c 'until curl -s http://localhost:8080 > /dev/null; do sleep 5; done'
 
       - name: ZAP Full Scan
-        uses: zaproxy/action-full-scan@v0.12.0 # He actualizado la versión de la acción también (opcional pero recomendado)
+        uses: zaproxy/action-full-scan@v0.12.0
         with:
-         
           docker_name: 'zaproxy/zap-stable'
-          token: ${{ secrets.GITHUB_TOKEN }}
           target: 'http://localhost:8080'
-          cmd_options: '-a -j -l WARN -z "-addoninstallall"'
+          cmd_options: '-a -j -l WARN'
           allow_issue_writing: false
 
-      - name: Upload HTML report
+      - name: Upload ZAP Report
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: DAST_Report
-          path: report_html.html
+          path: |
+            report_html.html
+            report_json.json
 
-      - name: Stop and clean up Docker container
+      - name: Cleanup
         if: always()
         run: |
           docker stop demoApp || true
           docker rm demoApp || true
-          docker container prune --force
-          docker image prune --force
+          docker system prune -af
